# Generated by Django 4.2.4 on 2023-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='phone_number',
            field=models.TextField(max_length=10),
        ),
    ]
