# Generated by Django 4.2.4 on 2023-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0003_alter_movie_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
